notificacao:
  host: https://api-apix.sensedia.com/notification/v1/notifications
  client:
    id: 67558253-50e0-399e-a9ed-5374d8959dfd
subscription:
  name: notificacoes-in
topic:
  out:
    name: notificacoes-out